[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]

remappings = [
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
]
ffi = true
gas_reports = ["*"]
solc = '0.8.20'
evm_version = 'paris'
# Enable optimizer
optimizer = true

# Number of optimization runs
optimizer_runs = 200

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismSepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
polygonAmoy = "${POLYGON_AMOY_RPC_URL}"
bnbChainTestnet = "${BNB_CHAIN_TESTNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
kromaSepolia = "${KROMA_SEPOLIA_RPC_URL}"
wemixTestnet = "${WEMIX_TESTNET_RPC_URL}"
gnosisChiado = "${GNOSIS_CHIADO_RPC_URL}"
celoAlfajores = "${CELO_ALFAJORES_RPC_URL}"
anvil = "${ANVIL}"

[dependencies]
forge-std = "^1.8.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
